<?php
    // Set up page title:
    $this->headTitle($this->translate('unsubscribe_confirmation'));
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="content unsubscribe">
    <?php if ($this->success): ?>
      <p><?=$this->transEsc('unsubscribe_successful'); ?></p>
    <?php else: ?>
      <p><?= $this->transEsc('unsubscribe_confirmation'); ?></p>
      <p>
        <a class="btn btn-primary" href="<?= $this->escapeHtml($this->unsubscribeUrl); ?>"><?= $this->transEsc('confirm_dialog_yes'); ?></a>
        <a class="btn btn-primary" href="<?= $this->url('home'); ?>"><?= $this->transEsc('confirm_dialog_no'); ?></a>
      </p>
    <?php endif; ?>
  </div>
</div>
